language: node_js
node_js:
  - "0.10"

branches:
  only:
    - master

before_install:
  - npm install bower -g
  - npm install gulp -g

script:
  - sudo apt-get install libfontconfig
  - npm install
  - bower install
  - gulp test

cache:
  directories:
  - bower_components
  - node_modules

notifications:
  email:
    - wardbell@hotmail.com

