language: node_js
node_js:
  - "0.10"

branches:
  only:
    - master

before_install:
  - npm install bower -g
  - npm install gulp -g
  - sudo yum install fontconfig freetype libfreetype.so.6 libfontconfig.so.1 libstdc++.so.6

script:
  - npm install
  - bower install
  - gulp test

cache:
  directories:
  - bower_components
  - node_modules

notifications:
  email:
    - wardbell@hotmail.com

